### ISSUE TITLE
Accent marks in Hebrew - example Goliath variations in text

### ISSUE THREAD

**Issue by BillMeyerRSA** [charlesLoder/hebrewTransliteration#54]
Goliath transliteration for example - my understanding as per SIL transliteration should be Ḡolyāṯ. Is there a way to handle the accents?
גָּלְיָ֥ת
גָּלְיָת
גָּלְיָת֩
גָּלְיָ֨ת
גָּלְיָ֥ת

**Comment by charlesLoder** [comment]
This is one is tricky. Because `גָּלְיָת` doesn't follow typical Hebrew syllabification (because it's not a semitic name), the [syllabification package](https://github.com/charlesLoder/havarotjs/blob/main/src/utils/qametsQatan.ts#L118-L128) doesn't catch it correctly.

```js
  for (const wholeWord of wholeWordsRegx) {
    const regEx = new RegExp(wholeWord);
    const match = noTaamim.match(regEx);


    if (!match) {
      continue;
    } else {
      const lastQam = word.lastIndexOf("\u{05B8}"); / / <-----  this is the problem
      return word.substring(0, lastQam) + "\u{05C7}" + word.substring(lastQam + 1);
    }
  }
```

I'll have to figure out a work around for that.

In the meantime, if you use [Sefaria](https://www.sefaria.org/I_Samuel.17.4?lang=bi), all the instances of the name already have a qamets qatan
